---
# tasks file for ansible-frr
- name: Run FRR Tasks
  block:
   - include_tasks: debian.yml
     when:
       - ansible_distribution == "Debian"
       - frr_version|float is version("7.0", ">=")
   - include_tasks: debian_legacy.yml
     when:
       - ansible_distribution == "Debian"
       - frr_version|float is version("7.0", "<")
   - include_tasks: debian.yml
     when:
       - ansible_distribution == "Ubuntu"
       - ansible_distribution_version < "20.04"
       - frr_version|float is version("7.0", ">=")
   - include_tasks: debian_legacy.yml
     when:
       - ansible_distribution == "Ubuntu"
       - ansible_distribution_version < "20.04"
       - frr_version|float is version("7.0", "<")
   - include_tasks: ubuntu.yml
     when:
       - ansible_distribution == "Ubuntu"
       - ansible_distribution_version >= "20.04"
   - include_tasks: redhat.yml
     when:
       - ansible_os_family == "RedHat"
       - frr_version|float is version("7.0", ">=")
   - include_tasks: redhat_legacy.yml
     when:
       - ansible_os_family == "RedHat"
       - frr_version|float is version("7.0", "<")
   - include_tasks: system_tuning.yml
   - include_tasks: config.yml
   - include_tasks: monitor.yml
     when:
       - frr_monitor == True
     tags:
       - frr-monitoring
  when: routing_type == "frr"

- include_tasks: quagga.yml
  when: routing_type == "quagga"

- include_tasks: rit.yml
